export const internshipOfficeOptions = [
  "Head Office",
  "SITE factory",
  "Lahore factory",
  "Port Qasim factory",
  "Karachi sales office",
  "Lahore sales office",
  "Multan sales office",
  "Islamabad sales office"
] as const;

export const applicationChannelOptions = [
  "career cell",
  "linkdin",
  "employee referal",
  "Head hunt",
  "through email"
] as const;

export const universityOptions = [
  "Liaquat University of Medical and Health Sciences, Jamshoro Sindh",
  "Mirpur University of Science and Technology (MUST), AJ&K",
  "National University of Sciences & Technology, Rawalpindi/ Islamabad (NUST)",
  "Quaid-i-Azam University, Islamabad",
  "University of Agriculture, Faisalabad",
  "University of Balochistan, Quetta",
  "University of Engineering & Technology, Lahore",
  "University of Karachi, Karachi",
  "University of Peshawar, Peshawar",
  "University of the Punjab, Lahore",
  "Allama Iqbal Open University, Islamabad (AIOU)",
  "Pir Mehr Ali Shah Arid Agriculture, University Rawalpindi",
  "Bahauddin Zakariya University, Multan",
  "Balochistan University of Information Technology & Management Sciences, Quetta",
  "COMSATS University, Islamabad",
  "DOW University of Health Sciences, Karachi",
  "Fatima Jinnah Women University, Rawalpindi",
  "Government College University, Faisalabad",
  "Government College University, Lahore",
  "Kohat University of Science and Technology, Kohat",
  "University of Engineering & Technology, Peshawar",
  "Mehran University of Engineering & Technology, Jamshoro",
  "National University of Modern Languages, Islamabad (NUML)",
  "Quaid-e-Awam University of Engineering, Sciences & Technology, Nawabshah",
  "Shaheed Benazir Bhutto Women University, Peshawar",
  "Sindh Agriculture University, Tandojam, Haydarabad",
  "The University of Agriculture, Peshawar",
  "University of Sargodha, Sargodha",
  "University of Sindh, Jamshoro",
  "University of Veterinary & Animal Sciences, Lahore",
  "Sardar Bahadur Khan Women University, Quetta",
  "Khyber Medical University, Peshawar",
  "Bahria University, Islamabad",
  "University of Gujrat, Gujrat",
  "Lahore College for Women University, Lahore",
  "Shah Abdul Latif University, Khairpur",
  "International Islamic University, Islamabad",
  "University of Health Sciences, Lahore",
  "Sukkur Institute of Business Administration, Sukkur",
  "Islamia University, Bahawalpur",
  "Gomal University, D.I. Khan",
  "Balochistan University of Engineering & Technology, Khuzdar",
  "Dawood University of Engineering & Technology, Karachi",
  "Hazara University, Mansehra",
  "University of Education, Lahore",
  "Virtual University of Pakistan, Lahore",
  "Institute of Space Technology, Islamabad (IST)",
  "Air University, Islamabad",
  "Abdul Wali Khan University, Mardan",
  "National Textile University, Faisalabad",
  "Kinnaird College for Women, Lahore",
  "University of Azad Jammu & Kashmir, Muzaffarabad",
  "University of Engineering & Technology, Taxila",
  "NED University of Engineering & Technology, Karachi",
  "Institute of Management Science, Peshawar (IMS)",
  "University of Malakand, Chakdara, Dir, Malakand",
  "Pakistan Institute of Engineering & Applied Sciences, Islamabad (PIEAS)",
  "Shahaeed Mohtarma Benazir Bhutto Medical University, Larkana",
  "Federal Urdu University of Arts, Sciences & Technology, Islamabad",
  "Lasbela University of Agriculture, Water and Marine Sciences, Lasbela",
  "University of Science & Technology, Bannu",
  "Institute of Business Administration, Karachi",
  "Islamia College University, Peshawar",
  "Pakistan Institute of Development Economics (PIDE), Islamabad",
  "Shaheed Benazir Bhutto University, Sheringal, Dir",
  "Karakurum International University, Gilgit",
  "National College of Arts, Lahore (NCA)",
  "King Edward Medical University, Lahore",
  "The Bolan University of Medical and Health Sciences, Quetta",
  "Riphah International University, Islamabad",
  "Institute of Business Management, Karachi",
  "Iqra University, Karachi",
  "Ilma University, Karachi",
  "Shaheed Zulfikar Ali Bhutto Institute of Sc. & Technology (SZABIST), Karachi",
  "Isra University, Hyderabad",
  "The University of Faisalabad, Faisalabad",
  "Beaconhouse National University, Lahore",
  "University of Management & Technology, Lahore",
  "Indus University, Karachi",
  "Zia-ud-Din University, Karachi",
  "Ghulam Ishaq Khan Institute of Engineering Sciences & Technology, Topi",
  "Dadabhoy Institute of Higher Education",
  "University of Lahore, Lahore",
  "National University of Computer and Emerging Sciences, Islamabad (FAST)",
  "Al-Hamd Islamic University, Quetta",
  "Benazir Bhutto Shaheed University Lyari, Karachi",
  "CECOS University of Information Technology and Emerging Sciences, Peshawar",
  "City University of Science and Information Technology, Peshawar",
  "DHA Suffa University, Karachi",
  "Foundation University, Islamabad",
  "Greenwich University, Karachi",
  "Habib University, Karachi",
  "Hamdard University, Karachi",
  "HITEC University, Taxila",
  "Iqra National University, Peshawar",
  "Karachi Institute of Economics & Technology, Karachi (PAF)",
  "Khadam Ali Shah Bukhari Institute of Technology, Karachi [KASB]",
  "Lahore School of Economics, Lahore",
  "National Defense University, Islamabad (NDU)",
  "Newport Institute of Communications & Economics, Karachi",
  "Northern University, Nowshera",
  "Peoples University of Medical and Health Sciences for Women, Nawabshah",
  "Pakistan Institute of Fashion and Design, Lahore",
  "Sarhad University of Science and Information Technology, Peshawar",
  "Shaheed Benazir Bhutto University, Shaheed Benazirabad",
  "Sindh Madresatul Islam University, Karachi",
  "Superior College, Lahore",
  "University of Poonch, Rawalakot",
  "University of Haripur, Haripur",
  "University of South Asia, Lahore",
  "University of Swabi",
  "University of Swat, Swat",
  "University of Turbat, Turbat",
  "University of Wah, Wah",
  "National College of Business Administration & Economics, Lahore",
  "Jinnah University for Women, Karachi",
  "GIFT University, Gujranwala",
  "Baqai Medical University, Karachi",
  "University of Central Punjab, Lahore",
  "Karachi School for Business Leadership, Karachi",
  "University of Kotli",
  "Qarshi University, Lahore",
  "Bacha Khan University, Charsadda",
  "Indus Valley School of Art and Architecture, Karachi",
  "Qurtuba University of Science and Information Technology, D.I. Khan",
  "Abasyn University",
  "Minhaj University, Lahore",
  "Hajvery University, Lahore",
  "Institute of Southern Punjab, Multan",
  "Commecs Institute of Business & Emerging Sciences, Karachi",
  "Gandhara University, Peshawar",
  "Aga Khan University, Karachi",
  "Government College for Women University, Faisalabad",
  "Imperial College of Business Studies, Lahore",
  "Jinnah Sindh Medical University, Karachi",
  "Khushal Khan Khattak University, Karak",
  "Muhammad Ali Jinnah University, Karachi",
  "Nazeer Hussain University, Karachi",
  "NFC Institute of Engineering & Technology, Multan",
  "Sir Syed University of Engg. & Technology, Karachi",
  "Women University of Azad Jammu and Kashmir Bagh",
  "Information Technology University of the Punjab, Lahore",
  "Mohi-ud-Din Islamic University, Narin Sharif, AJK",
  "Textile Institute of Pakistan, Karachi",
  "Lahore Garrison University, Lahore",
  "Capital University of Science and Technology, Islamabad",
  "Institute of Management Sciences, Lahore",
  "Lahore Leads University, Lahore",
  "Lahore University of Management Sciences (LUMS), Lahore",
  "Forman Christian College, Lahore (university status)",
  "Muhammad Nawaz Shareef University of Agriculture, Multan",
  "Government College Women University, Sialkot",
  "Ghazi University, Dera Ghazi Khan",
  "Gambat Institute of Medical Sciences, Khairpur",
  "Shaheed Benazir Bhutto University of Veterinary And Animal Sciences Sakrand",
  "MY University, Islamabad",
  "University of Loralai, Loralai",
  "Shaheed Benazir Bhutto Dewan University, Karachi",
  "Nur International University, Lahore",
  "Preston University, Karachi/Kohat",
  "Shaheed Benazir Bhutto City University, Karachi",
  "Shaheed Zulfiqar Ali Bhutto Medical University, Islamabad",
  "Shifa Tameer-e-Millat University, Islamabad",
  "Sindh Institute of Medical Sciences, Karachi",
  "University of FATA, Kohat",
  "Government Sadiq College Women University, Bahawalpur",
  "Shaheed Zulfiqar Ali Bhutto University of Law, Karachi",
  "Muhammad Nawaz Sharif University of Engineering & Technology, Multan",
  "Khwaja Fareed University of Engineering and IT, Rahim Yar Khan",
  "National University of Medical Sciences, Islamabad",
  "Abbottabad University of Science & Technology",
  "Benazir Bhutto Shaheed University of Technology & Skill Development, Khairpur",
  "Fatima Jinnah Medical University, Lahore",
  "Shuhda-e-Army Public School University of Technology, Nowshera",
  "Sindh Institute of Management & Technology",
  "Women University, Swabi",
  "University of Baltistan, Skardu",
  "Salim Habib University",
  "Rawalpindi Medical University",
  "Women University, Mardan",
  "BRAINS Institute, Peshawar",
  "Institute for Art and Culture, Lahore",
  "University of Engineering & Technology, Mardan",
  "National University of Technology, Islamabad",
  "University of Buner",
  "University of Okara",
  "University of Sialkot, Sialkot",
  "Cholistan University of Veterinary & Animal Sciences, Bahawalpur",
  "Emaan Institute of Management & Sciences, Karachi",
  "Faisalabad Medical University, Faisalabad",
  "Government College University, Hyderabad",
  "Namal University, Mianwali",
  "Nishtar Medical University Multan",
  "Punjab Tianjin University of Technology, Lahore",
  "Sir Syed (CASE) Institute of Technology, Islamabad",
  "Sohail University, Karachi",
  "University of Lakki Marwat",
  "University of Chitral",
  "University of Narowal",
  "University of Sahiwal",
  "University of Sufism and Modern Sciences, Bhitshah",
  "Rawalpindi Women University, Rawalpindi",
  "Health Services Academy",
  "Mir Chakar Khan Rind University, Sibi",
  "Pak-Austria Fachhochschule Institute of Applied Sciences and Technology, Haripur",
  "Begum Nusrat Bhutto Women University, Sukkur",
  "The Shaikh Ayaz University, Shikarpur",
  "University of Art and Culture, Jamshoro",
  "The Green International University, Lahore",
  "Times Institute, Multan",
  "University of Chakwal, Chakwal",
  "University of Home Economics, Lahore",
  "University of Mianwali",
  "Air War College Institute, Karachi",
  "Ibadat International University",
  "National Skills University",
  "Kohsar University",
  "Mir Chakar Khan Rind University of Technology, Dera Ghazi Khan",
  "University of Jhang",
  "Karachi Institute of Technology & Entrepreneurs, Karachi",
  "Metropolitan University, Karachi",
  "University of Modern Sciences, Tando Muhammad Khan",
  "UIT University, Karachi",
  "University of Agriculture, Dera Ismail Khan",
  "Sindh Institute Of Physical Medicine & Rehabilitation (SIPM&R), Karachi",
  "Malir University Of Science & Technology",
  "Al-Karam International Institute, Bhera",
  "Aror University Of Art, Architecture, Design And Heritage, Sukkur",
  "Ghazi National Institute Of Engineering And Sciences, Dera Ghazi Khan",
  "Lahore Institute Of Science & Technology, Lahore (LIST)",
  "Millennium Institute Of Technology And Entrepreneurship, Karachi (MITE)",
  "Punjab University Of Technology, Rasul-Mandi Bahauddin",
  "The Grand Asian University, Sialkot",
  "University of Chenab, Gujrat",
  "University of Gwadar",
  "University of Engineering & Applied Sciences, Swat",
  "Emerson University, Multan",
  "Multan University of Science & Technology, Multan",
  "International Institute of Science, Arts and Technology, Gujranwala",
  "University of Layyah",
  "Pakistan Global Institute, Rawat",
  "Rashid Latif Khan University",
  "Lahore University of Biological & Applied Sciences",
  "Ibn-e-Sina University",
  "Al Ghazali University",
  "Shaheed Allah Bukhsh Soomro University of Art, Design & Heritage",
  "University of Child Health Sciences",
  "Thal University, Bhakkar",
  "Hands Institute of Development Studies, Karachi",
  "Baba Guru Nanak University, Nankana Sahab (BGNU)",
  "The Azad Jammu & Kashmir University of Bhimber",
  "University of Makran, Panjgur",
  "Hyderabad Institute for Technology and Management Sciences",
  "National University of Pakistan",
  "Saifee Burhani University, Karachi",
  "Al-Kawthar University, Karachi",
  "The University of Agriculture, Swat",
  "Dar-ul-Madina International University, Islamabad"
] as const;
