import { addDays, subDays } from "date-fns";
import { InternshipType, InternStatus } from "@prisma/client";

const now = new Date();

export const mockDepartments = [
  { id: "cmf0dept00000000000000001", name: "Quality Assurance", createdAt: subDays(now, 120) },
  { id: "cmf0dept00000000000000002", name: "Finance", createdAt: subDays(now, 119) },
  { id: "cmf0dept00000000000000003", name: "HR", createdAt: subDays(now, 118) },
  { id: "cmf0dept00000000000000004", name: "Marketing", createdAt: subDays(now, 117) },
  { id: "cmf0dept00000000000000005", name: "Supply Chain", createdAt: subDays(now, 116) },
  { id: "cmf0dept00000000000000006", name: "R&D", createdAt: subDays(now, 115) },
  { id: "cmf0dept00000000000000007", name: "IT", createdAt: subDays(now, 114) },
  { id: "cmf0dept00000000000000008", name: "Operations", createdAt: subDays(now, 113) }
];

export const mockSupervisors = mockDepartments.flatMap((department, index) => [
  {
    id: `cmf0sup${index}000000000000000001`,
    name: `${department.name} Supervisor 1`,
    email: `${department.name.toLowerCase().replace(/[^a-z0-9]+/g, ".")}1@daldafoods.com`,
    contactNumber: "03001234567",
    departmentId: department.id
  },
  {
    id: `cmf0sup${index}000000000000000002`,
    name: `${department.name} Supervisor 2`,
    email: `${department.name.toLowerCase().replace(/[^a-z0-9]+/g, ".")}2@daldafoods.com`,
    contactNumber: "03007654321",
    departmentId: department.id
  }
]);

export const mockInterns = [
  {
    id: "cmf0intern0000000000000001",
    fullName: "Ayesha Khan",
    fatherName: "Javed Khan",
    cnicNumber: "42101-1234567-8",
    contactNumber: "03001234567",
    email: "ayesha.khan@example.com",
    city: "Karachi",
    address: "Clifton Block 5, Karachi",
    university: "IBA Karachi",
    officeLocation: "Head Office",
    degree: "BBA",
    major: "Marketing",
    currentSemester: 7,
    graduationYear: 2026,
    departmentId: mockDepartments[2].id,
    durationWeeks: 8,
    internshipType: InternshipType.PROJECT_BASED,
    applicationSource: "University career drive",
    knownEmployee: "",
    comments: "Strong communication skills",
    reference: "HR-2026-001",
    testScore: 88,
    testDate: subDays(now, 18),
    supervisorId: mockSupervisors[4].id,
    supervisorName: mockSupervisors[4].name,
    supervisorEmail: mockSupervisors[4].email,
    joiningDate: subDays(now, 14),
    endDate: addDays(now, 4),
    status: InternStatus.ACTIVE,
    extraNotes: "Potential management trainee candidate",
    cvFile: null,
    certificateFile: null,
    reportFile: null,
    createdAt: subDays(now, 15),
    updatedAt: subDays(now, 2),
    department: mockDepartments[2],
    supervisor: mockSupervisors[4],
    addedBy: { id: "seed-hr", name: "HR Officer" },
    extensionLogs: [],
    evaluation: null
  },
  {
    id: "cmf0intern0000000000000002",
    fullName: "Bilal Ahmed",
    fatherName: "Aslam Ahmed",
    cnicNumber: "42201-2345678-9",
    contactNumber: "03002345678",
    email: "bilal.ahmed@example.com",
    city: "Lahore",
    address: "Johar Town, Lahore",
    university: "LUMS",
    officeLocation: "Lahore sales office",
    degree: "Computer Science",
    major: "Software Engineering",
    currentSemester: 8,
    graduationYear: 2026,
    departmentId: mockDepartments[6].id,
    durationWeeks: 10,
    internshipType: InternshipType.ONGOING,
    applicationSource: "LinkedIn application",
    knownEmployee: "Farhan Malik",
    comments: "Returning intern",
    reference: "IT-2026-009",
    testScore: 91,
    testDate: subDays(now, 31),
    supervisorId: mockSupervisors[12].id,
    supervisorName: mockSupervisors[12].name,
    supervisorEmail: mockSupervisors[12].email,
    joiningDate: subDays(now, 28),
    endDate: addDays(now, 12),
    status: InternStatus.EXTENDED,
    extraNotes: "Needs final project review",
    cvFile: null,
    certificateFile: null,
    reportFile: null,
    createdAt: subDays(now, 30),
    updatedAt: subDays(now, 1),
    department: mockDepartments[6],
    supervisor: mockSupervisors[12],
    addedBy: { id: "seed-hr", name: "HR Officer" },
    extensionLogs: [
      {
        id: "log-1",
        previousEndDate: addDays(now, 5),
        newEndDate: addDays(now, 12),
        reason: "Support final sprint wrap-up",
        createdAt: subDays(now, 2),
        extendedBy: { name: "HR Officer" }
      }
    ],
    evaluation: null
  },
  {
    id: "cmf0intern0000000000000003",
    fullName: "Fatima Noor",
    fatherName: "Sajid Noor",
    cnicNumber: "42301-9876543-2",
    contactNumber: "03003456789",
    email: "fatima.noor@example.com",
    city: "Islamabad",
    address: "G-11 Markaz, Islamabad",
    university: "NUST",
    officeLocation: "SITE factory",
    degree: "Chemical Engineering",
    major: "Process Engineering",
    currentSemester: 8,
    graduationYear: 2025,
    departmentId: mockDepartments[0].id,
    durationWeeks: 6,
    internshipType: InternshipType.PROJECT_BASED,
    applicationSource: "Campus ambassador referral",
    knownEmployee: "",
    comments: "",
    reference: "QA-2026-004",
    testScore: 84,
    testDate: subDays(now, 60),
    supervisorId: mockSupervisors[0].id,
    supervisorName: mockSupervisors[0].name,
    supervisorEmail: mockSupervisors[0].email,
    joiningDate: subDays(now, 52),
    endDate: subDays(now, 7),
    status: InternStatus.COMPLETED,
    extraNotes: "Submitted strong final report",
    cvFile: null,
    certificateFile: null,
    reportFile: null,
    createdAt: subDays(now, 55),
    updatedAt: subDays(now, 6),
    department: mockDepartments[0],
    supervisor: mockSupervisors[0],
    addedBy: { id: "seed-admin", name: "Dalda Admin" },
    extensionLogs: [],
    evaluation: {
      punctuality: 5,
      technicalSkills: 4,
      communication: 5,
      teamwork: 5,
      initiative: 4,
      overallScore: 4.6,
      remarks: "A dependable intern with strong ownership."
    }
  }
];
